global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'nestjs-app'
        static_configs:
          - targets: ['cd-app-service.azurewebsites.net:80']